fixtures:
  repositories:
    concat:   'git://github.com/theforeman/puppet-concat'
    dhcp:     'git://github.com/theforeman/puppet-dhcp'
    dns:      'git://github.com/theforeman/puppet-dns'
    foreman:  'git://github.com/theforeman/puppet-foreman'
    puppet:   'git://github.com/theforeman/puppet-puppet'
    tftp:     'git://github.com/theforeman/puppet-tftp'
    xinetd:   'git://github.com/puppetlabs/puppetlabs-xinetd.git'


  symlinks:
    foreman_proxy: "#{source_dir}"
