fixtures:
  repositories:
    apt:      'git://github.com/puppetlabs/puppetlabs-apt'
    concat:   'git://github.com/puppetlabs/puppetlabs-concat'
    datacat:  'git://github.com/richardc/puppet-datacat'
    dhcp:     'git://github.com/theforeman/puppet-dhcp'
    dns:      'git://github.com/theforeman/puppet-dns'
    extlib:   'git://github.com/voxpupuli/puppet-extlib'
    foreman:  'git://github.com/theforeman/puppet-foreman'
    mysql:    'git://github.com/puppetlabs/puppetlabs-mysql.git'
    puppet:   'git://github.com/theforeman/puppet-puppet'
    stdlib:   'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    tftp:     'git://github.com/theforeman/puppet-tftp'
    xinetd:   'git://github.com/puppetlabs/puppetlabs-xinetd.git'


  symlinks:
    foreman_proxy: "#{source_dir}"
    test: "#{source_dir}/spec/static_fixtures/test_module"
