fixtures:
  repositories:
    apt:      'https://github.com/puppetlabs/puppetlabs-apt'
    augeas_core:
      repo: 'https://github.com/puppetlabs/puppetlabs-augeas_core'
      puppet_version: '>= 6.0.0'
    concat:   'https://github.com/puppetlabs/puppetlabs-concat'
    cron_core:
      repo: "https://github.com/puppetlabs/puppetlabs-cron_core"
      puppet_version: ">= 6.0.0"
    datacat:  'https://github.com/richardc/puppet-datacat'
    dhcp:     'https://github.com/theforeman/puppet-dhcp'
    dns:      'https://github.com/theforeman/puppet-dns'
    extlib:   'https://github.com/voxpupuli/puppet-extlib'
    foreman:  'https://github.com/theforeman/puppet-foreman'
    mysql:    'https://github.com/puppetlabs/puppetlabs-mysql'
    puppet:   'https://github.com/theforeman/puppet-puppet'
    stdlib:   'https://github.com/puppetlabs/puppetlabs-stdlib'
    systemd:  'https://github.com/camptocamp/puppet-systemd'
    tftp:     'https://github.com/theforeman/puppet-tftp'
    xinetd:   'https://github.com/puppetlabs/puppetlabs-xinetd'
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core"
      puppet_version: ">= 6.0.0"
