fixtures:
  repositories:
    apt:      'https://github.com/puppetlabs/puppetlabs-apt'
    concat:   'https://github.com/puppetlabs/puppetlabs-concat'
    datacat:  'https://github.com/richardc/puppet-datacat'
    dhcp:     'https://github.com/theforeman/puppet-dhcp'
    dns:      'https://github.com/theforeman/puppet-dns'
    extlib:   'https://github.com/voxpupuli/puppet-extlib'
    foreman:  'https://github.com/theforeman/puppet-foreman'
    mysql:    'https://github.com/puppetlabs/puppetlabs-mysql'
    puppet:   'https://github.com/theforeman/puppet-puppet'
    stdlib:   'https://github.com/puppetlabs/puppetlabs-stdlib'
    systemd:  'https://github.com/camptocamp/puppet-systemd'
    tftp:     'https://github.com/theforeman/puppet-tftp'
    xinetd:   'https://github.com/puppetlabs/puppetlabs-xinetd'


  symlinks:
    foreman_proxy: "#{source_dir}"
    test: "#{source_dir}/spec/static_fixtures/test_module"
