---
.travis.yml:
  beaker_sets:
    - docker/centos-7
    - docker/debian-9
  env:
    global:
      - PARALLEL_TEST_PROCESSORS=8
Rakefile:
  param_docs_pattern:
    - manifests/init.pp
    - manifests/plugin/**/*.pp
