name    'theforeman-foreman_proxy'
version '2.0.2'
source 'git://github.com/theforeman/puppet-foreman_proxy'
author 'theforeman'
license 'GPLv3+'
summary 'Foreman Smart Proxy configuration'
description 'Module for configuring the Foreman Smart Proxy and other services'
project_page 'http://github.com/theforeman/foreman-installer'

dependency 'puppetlabs/stdlib', '>= 2.3.0'
dependency 'theforeman/dns', '>= 1.3.0'
dependency 'theforeman/dhcp', '>= 1.3.0'
dependency 'theforeman/foreman', '>= 1.3.0'
dependency 'theforeman/puppet', '>= 1.3.0'
dependency 'theforeman/tftp', '>= 1.3.0'
